#!/usr/bin/env bash

echo "===  {START}: Building AggroLlama-Z3 [Pure Vulkan + Aggressive LTO!]  ==="

set -e

source /opt/AMD/aocc-compiler-*/setenv_AOCC.sh
AOCC="/opt/AMD/aocc-compiler-5.2.0/bin"

export AGGRO="-march=native -mtune=znver3 -Ofast -flto=auto -ffat-lto-objects -funroll-loops -ftree-vectorize -mprefer-vector-width=256 -ffast-math -fomit-frame-pointer -fstrict-aliasing -mllvm -align-all-nofallthru-blocks=5 -fno-finite-math-only -Wno-pass-failed"
export OMP_PROC_BIND=TRUE

cd "$HOME/.src/llama.cpp"
rm -rf build

git fetch --all
git fetch --tags --all
git reset --hard
git pull

cmake -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="${AOCC}/clang" \
    -DCMAKE_CXX_COMPILER="${AOCC}/clang++" \
    -DCMAKE_C_FLAGS="$AGGRO" \
    -DCMAKE_CXX_FLAGS="$AGGRO" \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
    -DGGML_NATIVE=ON \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DCMAKE_EXE_LINKER_FLAGS="-s -lmimalloc -flto=auto -Wl,--allow-multiple-definition" \
    -DCMAKE_SHARED_LINKER_FLAGS="-s -lmimalloc -flto=auto -Wl,--allow-multiple-definition" \
    -DCMAKE_MODULE_LINKER_FLAGS="-s -lmimalloc -flto=auto -Wl,--allow-multiple-definition" \
    -DGGML_MIMALLOC=ON \
    -DCMAKE_INSTALL_RPATH="\$ORIGIN" \
    -DGGML_BACKEND_DL=OFF \
    -DGGML_VULKAN=ON

ninja -C build

echo "===  {END}: AggroLlama-Z3 Pure Vulkan Build Completed!  ==="

